apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidomysqldeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:8.0.32
          ports:
            - containerPort: 3306
              name: mysqlport
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: covidomysqlsecret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlvolume
      volumes:
        - name: mysqlvolume
          persistentVolumeClaim:
            claimName: covidomysqlpvc