apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: covidomysqlpvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: covidostorageclass
